PixelGameEngine Tutorials
GaxysGalactic/TG-Training-CPP pull request #12
Opened 2022-10-07 15:23 UTC by GaxysGalactic

Includes all the PixelGameEngine tutorials done so far:
- Flappy Bird
- Asteroids
- Pathfinding (A*)

2022-10-07 17:04 UTC, DvdHalliday requested changes
Good job!

This is some clean code right here. There's a couple of comments you might wanna check

2022-10-07 17:04 UTC, DvdHalliday commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +		// Name your application
Unnecessary comment

2022-10-07 17:04 UTC, DvdHalliday commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +		FNode* Parent;
Maybe add some separating blank lines to group common attributes?

2022-10-07 17:04 UTC, DvdHalliday commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +		std::vector<FNode*> Neighbours;
our coding standards state we should be using US spelling for variable names

2022-10-07 17:04 UTC, DvdHalliday commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +		int y;
I'm not sure but... according to standards maybe these two should be capitilised?

2022-10-07 17:04 UTC, DvdHalliday commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +	int NodeInner = NodeSize - (NodeBorder * 2);
>;o

2022-10-07 17:04 UTC, DvdHalliday commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +	FNode* NodeEnd = nullptr;
Perhaps Node at the end of the variable name would make more sense? i think Javid names them like these 'cause of his own naming conventions, just as he names vecNodes... and such, bur for us I think StartNode would probably be best, what do you think?

2022-10-07 17:04 UTC, DvdHalliday commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +	void ConnectOrthogonally(const int& x, const int& y)
built-in parameters shouldn't be referenced

2022-10-07 17:04 UTC, DvdHalliday commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +	void ConnectDiagonally(const int& x, const int& y)
built-in parameters shouldn't be referenced

2022-10-07 17:04 UTC, DvdHalliday commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +
Interesting, however if you leave both commented out you're gonna' create double connections between each node, won't you?

2022-10-07 17:04 UTC, DvdHalliday commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +		//Use integer division to nicely get cursor position in node space
BUT HOW NICELY IS IT REALLY, HUH?

2022-10-07 17:04 UTC, DvdHalliday commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +		};
Lovely

2022-10-07 17:04 UTC, DvdHalliday commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +					Neighbour->GlobalGoal = Neighbour->LocalGoal + Heuristic(Neighbour, NodeEnd);
looks good to me

2022-10-07 17:04 UTC, DvdHalliday commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +	void SolveAStar()
It looks good, however yup I think it's a bit long so you might want to consider separating some chunks of it into different functions

2022-10-10 13:26 UTC, simonkytr commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +class Pathfinding : public olc::PixelGameEngine
according to the coding standards, you have to name this class with the f prefix

2022-10-10 13:26 UTC, simonkytr commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +		int y;
or maybe you should name like "PositionX"

2022-10-10 20:02 UTC, GaxysGalactic commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +
If I leave both commented, there are no connections between nodes. It looks kinda sad. 

![image](https://user-images.githubusercontent.com/44332093/194943663-bdf7ce0d-1c64-46aa-8e81-178f9722183c.png)

2022-10-11 03:26 UTC, sancho6040 reviewed
my congratulations to the chef. 👌

2022-10-11 03:26 UTC, sancho6040 commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +		return true;
great work with the organization of your code 👌

2022-10-11 03:26 UTC, sancho6040 commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +
Why would you comment both methods if this will cause the program to do nothing?? Xd

2022-10-11 03:26 UTC, sancho6040 commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +		};
May be here you can use the method pow from "Math. h", this will make the code more readable.

2022-10-11 03:26 UTC, sancho6040 commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +		auto Heuristic = [Distance](FNode* a, FNode* b)
I don't know about these parameter names, should it be Uppercase? The same for the cases where you use x and y?
What does @JD say about this?

2022-10-11 16:04 UTC, JDAlzate reviewed
Nice code, but be careful with conventions and calling your variables `n`, `a`, `b`, `x`, etc.

2022-10-11 16:04 UTC, JDAlzate commented on Projects/PixelGameEngine/PixelTutorials/Asteroids/main.cpp
> +		float X;
I have no clue what X, Y, dX, and dY is for a SpaceObject 👀. Also dX and dY do not follow conventions.

2022-10-11 16:04 UTC, JDAlzate commented on Projects/PixelGameEngine/PixelTutorials/Asteroids/main.cpp
> +	struct SpaceObject
structs and classes should start with F

2022-10-11 16:04 UTC, JDAlzate commented on Projects/PixelGameEngine/PixelTutorials/Asteroids/main.cpp
> +			float a = ((float)i / (float)Verts) * 6.28318f;
What is a 👀

2022-10-11 16:04 UTC, JDAlzate commented on Projects/PixelGameEngine/PixelTutorials/Asteroids/main.cpp
> +	void UpdateShipPhysics(float& ElapsedTime)
Why are these floats passed-in as references?

2022-10-11 16:04 UTC, JDAlzate commented on Projects/PixelGameEngine/PixelTutorials/Asteroids/main.cpp
> +		for (SpaceObject& a : Asteroids)
I don't know what a means. But I can see that it is not being changed, so this should be a const reference 👀 Remember that non-const references are for objects that are intended to be changed.

2022-10-11 16:04 UTC, JDAlzate commented on Projects/PixelGameEngine/PixelTutorials/Asteroids/main.cpp
> +		for (SpaceObject& a : Asteroids)
I see a trend in the whole project to use unnecessary references for built-in data types and non-const references for instances that don't need to change.

2022-10-11 16:04 UTC, JDAlzate commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +		Nodes = new FNode[MapWidth * MapHeight];
Smells like a memory leak 👀 I couldn't find a delete anywhere.

Keep in mind that we want to avoid raw pointers and naked new allocations when possible. This is why containers exist, so this memory leak could have been avoided if Nodes wasn't a pointer but rather a vector or some other container.

2022-10-11 16:04 UTC, JDAlzate commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +		for (int x = 0; x < MapWidth; x++)
I get it may be confusing, but the only acceptable exception for indices are i,j,k since they are universally known. If you're changing the name, you need to follow standards, so this should be an uppercase X, same as the Y.

2022-10-11 16:04 UTC, JDAlzate commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +			Nodes[y * MapWidth + x].Neighbors.push_back(&Nodes[(y - 1) * MapWidth + (x + 0)]);
This is a good place for helper functions. You're using the `Nodes[y * MapWidth + x]` a lot, and it's not very easy to read. A `GetNode(x, y)` would do wonders for readability.

2022-10-11 16:04 UTC, JDAlzate commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +		StartNode = &Nodes[(MapHeight / 2) * MapWidth + 1];
It's annoying to deal with instances directly and need to use the & operator every time. You could avoid this by having an array of pointers instead of an array of instances, with each node allocated in the heap.

2022-10-11 16:04 UTC, JDAlzate commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +		auto Distance = [](FNode* a, FNode* b)
a and b do not follow conventions.

2022-10-11 17:50 UTC, camodesigns commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +class Pathfinding : public olc::PixelGameEngine
F in Capital Letters

2022-10-11 17:50 UTC, camodesigns commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +	bool OnUserUpdate(float ElapsedTime) override
The name could be more specific, javi does it that way but it is not what we are looking for

2022-10-11 17:50 UTC, camodesigns commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +	bool OnUserCreate() override
The name could be more specific, javi does it that way but it is not what we are looking for

2022-10-11 17:50 UTC, camodesigns commented on Projects/PixelGameEngine/PixelTutorials/Pathfinding/main.cpp
> +					Neighbour->GlobalGoal = Neighbour->LocalGoal + Heuristic(Neighbour, NodeEnd);
for me too, so cool

2022-10-21 21:12 UTC, merged